server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址
      discovery:
        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则，这个规则优先会寻找与自己同集群的服务

feign:
  httpclient:
    enabled: true  #Enables the use of the Apache HTTP Client by Feign.(Default:true) 只不过maven没有导httpclient的包的话是不会实现的
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数

#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://localhost:10086/eureka